server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3307/identity_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: leovmika68
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

grpc:
  server:
    port: 9090

jwt:
  secret: 2a0e929f81eb06a0b9eba5a39e24e91966608eee54bcb9ab
  expiration: 86400000 # 1 day
  refresh-expiration: 604800000

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/identity_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
