server:
  port: 8082

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:mysql://localhost:3307/post_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: leovmika68
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: posts
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

grpc:
  client:
    identity-service:
      address: 'discovery:///identity-service'
      enable-keep-alive: true
      negotiation-type: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/post_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  minio:
    endpoint: http://minio:9000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/